### ISSUE TITLE
Missing Dependencies in requirement.txt

### ISSUE THREAD

**Issue by Fredpwol** [Fredpwol/Image-Steg#5]
I get this error when I try to run `flask run`

```
Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/home/feng/.local/lib/python3.8/site-packages/flask/cli.py", line 214, in locate_app
    __import__(module_name)
  File "/home/feng/Documents/code/Image-Steg/app.py", line 1, in <module>
    from main import app
  File "/home/feng/Documents/code/Image-Steg/main/__init__.py", line 3, in <module>
    from flask_bootstrap import Bootstrap
ModuleNotFoundError: No module named 'flask_bootstrap'
```

and when I run `pip install -r requirement.txt` no additional packages are downloaded.

### Resolution
Update the requirement.txt file

**Comment by shakurah** [comment]
Alright requirements.txt will be updated as soon as possible thanks
